### ISSUE TITLE
not porting branch history make diff useless

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [peteruhnak/git-migration#18]
Hi, I understand that it is difficult to port branches history across several packages: information is missing as whether package_P.branch_2 relates to package_Q.branch_4...

Since most MC branches are nameless, there is no hint for resolving such dilemma.

But I'm convinced that we can do better, and we should do better.

Simple cases first: for a single package, it's perfectly doable (see for example https://github.com/hpi-swa/Squot).
Example of simple MC branches with versions A B C D:

        *-B---*
       /       \
    A-*         *-D
       \       /
        *---C-*

will appear as:

    A---B---C---D

when we search what C was good for, we see diffs between parallel branches B and C, that is all diffs between A and B, (B-A) union all diffs between A and C (C-A)... It's exactly the MC reparent option which was proposed recently in Squeak, and which is kind of dangerous for these reasons.

If (B-A) is big, (it might in fact span several commits), then we completely loose the point of C, and history becomes useless. That's why we should do better if we can. It occurs quite often in VMMaker for example, see https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/305

In case of single package P, then I would say reproduce P topology.

For multi-package, I have some ideas (and heuristics), but it will be too long to discuss here.
I will try to think longer about details and gather them into another place.
 
For now, if we don't want to enter into multi-package parallel branches complexity, then the least we can do is to **rebase** C on B (with automatic conflict resolution on _ours_, that is, newest wins). At least, the diff will be relevant (modulo the conflicts, but conflicts are kind of relevant too, aren't they?).

This may not work so well when renaming classes/methods in one of the branches, because MC does not track such operation, but in most cases, it will lead to a more useful diff than we are getting now.

Also, the commit message should contain meta-information of which MC version is committed, and what special operation (rebase or reparent) did take place at translation.

**Comment by nicolas-cellier-aka-nice** [comment]
If at least the SHA of true parent of version C were mentioned in commit message, then this would leave a chance to display the correct diff, maybe not thru web, but via more elaborated git client, or command line. That's far from ideal but really low hanging.

**Comment by ThierryGoubier** [comment]
Hi Nicolas,

could you frame it as a graph building algorithm? Having such a description
would help checking the code.

Side note. Using the git fast-import interface in fact allows us to do
anything we like in term of how the graph is shaped, and conflicts do not
apply since we provide the solution to git along with the graph.

Le mer. 14 nov. 2018 à 15:28, Nicolas Cellier <notifications@github.com> a
écrit :

**Comment by peteruhnak** [comment]
> Hi, I understand that it is difficult to port branches history across several package
> Since most MC branches are nameless

MC having named branches is news to me, so that's probably the reason why they are not supported.

> then the least we can do is to rebase C on B

What if there's no code for B?
It is extremely common that although some versions are in the ancestry, there's no associated code for that...
so if I modify your example...

```
          *-B---*
          /          \
X-*-A-*         *--D-Y
          \          /
          *---C-*
```

Maybe only code for _X_ and _Y_ is available. Or only for X, C, Y.

And they don't even need to share common ancestor; you can have multiple commits without parents within the same package.

```
S ----*----B
                  \
                    *---D
                  /
Y ----*----A
```

then combine it all together, add a pile of other breaking edge cases and you are in hell. E.g. from PolyMath (purple boxes are commits without MCZs, yellow ones are commits without any parent):

![image](https://user-images.githubusercontent.com/1276328/48567364-24688680-e8fd-11e8-87e3-2300c2f24662.png)


I've spent way too much time on this when I started developing git-migration, but in the end I gave up because dealing with it was bullshit. I most definitely have no interest in spending another 30 hours trying to address this again. But feel free to open a PR or ask about internal details. I imagine if you are trying to address it for a specific project it can be much much easier.

> Also, the commit message should contain meta-information of which MC version is committed, and what special operation (rebase or reparent) did take place at translation.

The message is constructed in `GitMigrationCommitInfo>>commitMessage`. You have access to the `MCVersionInfo` which contains both the MC version, as well as the ancestry so it should be easy to change. I am not entirely sure whether I did a pass and removed ancestors that do not have any MCZ.. so you would need to check for each ancestor if there's a code to merge with at all.

> (rebase or reparent)

I gave up on trying to address merges properly. So right now it doesn't add anything (which by default means the previous commit is parent). Only for the very first commit I write the initial SHA (see `GitMigrationTonelWriter>>writeVersion:`

However it is not hard to add actual merges/rebases, assuming you know what you are merging.

Take a look at `GitFastImportFileWriter>>writeMergesFor:` and tests for this method. 

> This may not work so well when renaming classes/methods in one of the branches,

Renames in Git are implicit when you explicitly ask when listing history. For methods it doesn't apply (because the output is in tonel, not filetree), but classes should be ok (I think you can tweak how much the file can change for git to still consider it a rename).

> could you frame it as a graph building algorithm? Having such a description would help checking the code.

I'm not sure if the visualization still works (I haven't used it in a while and I've made quite a few changes since), but it is using some internal parts of GitMigration to acquire the history graphs.

**Comment by nicolas-cellier-aka-nice** [comment]
Thierry, in case we are flattening the graph into a single (chronological) line, what I want is that the diff remain relevant.

The tricky details is about conflicts, especially in case of alternate commits:

        *-B1----B2---*
       /              \
    A-*                *-D
       \              /
        *---C1----C2-*

Let's use following notations

- `Y\X` the diff of snapshot `Y` wrt `X`
- `+Y\X'`  the application of diffs `Y\X` over current head
- `Y>X` the set of conflict between `Y` and `X` with resolution to `Y`

Instead of this one which will lead to irrelevant diffs:

    A--B1--C1--B2--C2--D

the flattening should rather be decomposed into these steps, with intermediate commits in case of conflicts:

    A--B1--+C1>B1--+C1\A--+B1>C1--+B2\B1--+C2>B2--+C2\C1--D

The tricky part is that we need to reverse conflict resolution `C1>B1` when returning to branch B...
To do so, take parent of B2 (B1), extract conflict between current head and B1, apply them with resolution to B1.
This is easily extendable to several branches.
Each trick would deserve explicative commit message, and reference to true parent.

We could reorder B1-B2 then C1-C2 instead of chronological in order to reduce the # of conflict commits, but not when we have other packages intermixing...

Yet another detail might occur: when a class/method was moved to another package...
We thus need to compare package_P and package_Q: they don't have common ancestors, but they may have conflicts, at least a classification conflict. I didn't inquire if/how this case was handled right now.

In case when we want to preserve a bit more the original topology, I need to sketch my idea on paper first, because in MC we have parallel graphs (one per package) which seem completely unordered (except chronologically). My idea is to infer related branches package_P.branch_A goes with package_Q.branch_B based on heuristics: vicinity of commit dates (and or method dates), identity of committer (or individual method authors). But unlike flattening, this does not necessarily scale well to N branches, so I need more time to think about it.

In case when MCM or Metacello configurations are used, there are additional data about inter-package synchronization points which is valuable too (it is the possible to identify some of the relationships package_P.branch_A goes with package_Q.branch_B).

**Comment by nicolas-cellier-aka-nice** [comment]
Peter: yes, there are many edge cases, kudos for having pushed this package!

For missing .mcz, just compress the history (let's call that squashing...)
For parent-less .mcz, it's either a bug of the client (not a Squeak one I presume) or more or less intentional messing at low level (thru inspectors). We could try to either repair (based on chronological ancestor that minimize diffs), or just root them all to the same empty root package.

**Comment by peteruhnak** [comment]
I no longer maintain this project.

Please reopen any issues in the community-owned repo https://github.com/pharo-contributions/git-migration .
